PODS-8821 - Add Event 24/25 Manual Journey
hmrc/pension-scheme-event-reporting-frontend pull request #292
Opened 2023-11-07 15:41 UTC by LauraToddCodes

2023-11-08 18:17 UTC, PavelVjalicin requested changes

2023-11-09 19:51 UTC, PavelVjalicin commented on conf/app.routes
I think the following is missing from here:
GET         /report/remove-24                                                controllers.common.RemoveEventController.onPageLoad(waypoints: Waypoints ?= EmptyWaypoints, eventType: EventType = Event24)
POST        /report/remove-24                                                controllers.common.RemoveEventController.onSubmit(waypoints: Waypoints ?= EmptyWaypoints, eventType: EventType = Event24)

App crashes for me when trying to start a new event report for year 2022 and earlier.

2023-11-13 10:08 UTC, LauraToddCodes commented
@PavelVjalicin Thanks for the review - I've pushed changes to resolve the issues with apostrophes in the messages, test routes in the prod.routes file and the missing `report/remove-24` route. Do you know if any changes are needed for filtering of events in the `EventSelectionController`?

2023-11-13 10:32 UTC, jamdade-sharad commented on app/controllers/EventSelectionController.scala
> +      case false => Seq(Event24)
@PavelVjalicin : 
This is correct, if selected tax year is 2024 onwards then need to hide Event2, 6, 7, 8 and 8A 
and before 2024 hide the Event24.

it means Event24(previously known as Event25) only visible year2024 onwards.

2023-11-13 11:54 UTC, PavelVjalicin commented on app/controllers/EventSelectionController.scala
> +      case false => Seq(Event24)
I've tested the above seems to work properly.

2023-11-13 13:59 UTC, PavelVjalicin commented
> @PavelVjalicin Thanks for the review - I've pushed changes to resolve the issues with apostrophes in the messages, test routes in the prod.routes file and the missing `report/remove-24` route. Do you know if any changes are needed for filtering of events in the `EventSelectionController`?

I've tested this. Seems to work as intended.

2023-11-13 13:59 UTC, PavelVjalicin approved these changes
LGTM

2023-11-13 14:18 UTC, merged