PODS-7671 fixing node name for memberdetails
hmrc/pension-scheme-event-reporting-frontend pull request #64
Opened 2022-11-16 10:55 UTC by maryiahmansha

2022-11-16 11:06 UTC, cyeniceri requested changes

2022-11-16 11:06 UTC, cyeniceri commented on app/controllers/common/MembersDetailsController.scala
> +        println("\n\n Page :" + page)
println ? can you remove this ?

2022-11-16 11:07 UTC, emrawsy commented on app/controllers/common/MembersDetailsController.scala
> +        println("\n\n Page :" + page)
remove println

2022-11-16 15:05 UTC, cyeniceri submitted a review, later dismissed

2022-11-17 07:08 UTC, grantrobson approved these changes

2022-11-17 07:08 UTC, merged